version: '3.8'

services:
  master:
    image: mysql:5.7
    container_name: mysql-master
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - mysql-networks

  slave:
    image: mysql:5.7
    container_name: mysql-slave
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./slave/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql-networks

networks:
  mysql-networks:
    driver: bridge
